#!/usr/bin/env python3

# Configurar la zona horaria de Venezuela
__import__('os').environ['TZ'] = 'America/Caracas'

# Importar el módulo time después de configurar la zona horaria
import time
time.tzset()

# Importar Odoo
import odoo

if __name__ == "__main__":
    # Evitar datos de demostración y ejecutar Odoo
    odoo.cli.main(['--without-demo=all'])
