
[options]
bin_path = "C:\wkhtmltopdf\bin"
workers = 4
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 60
limit_time_real = 120
max_cron_threads = 2
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0
